"""Initial migration for tenants application.

This migration creates the initial Tenant and Domain models required for multitenancy.
"""

# Generated by Django 5.2.2 on 2025-06-08 23:32

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for creating tenant and domain models.

    This migration is responsible for creating the initial database schema
    for the tenant application, setting up the Tenant and Domain models
    required for django-tenants to function properly.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre comercial del negocio",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "created_on",
                    models.DateField(auto_now_add=True, verbose_name="Fecha de creación"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email de contacto principal",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono de contacto",
                        max_length=20,
                        null=True,
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el tenant está activo",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "on_trial",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el tenant está en período de prueba",
                        verbose_name="En prueba",
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha en que termina el período de prueba",
                        null=True,
                        verbose_name="Fin de prueba",
                    ),
                ),
                (
                    "paid_until",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la que el tenant ha pagado",
                        null=True,
                        verbose_name="Pagado hasta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inquilino",
                "verbose_name_plural": "Inquilinos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si este es el dominio principal para el tenant",
                        verbose_name="Dominio principal",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dominio",
                "verbose_name_plural": "Dominios",
                "ordering": ["domain"],
            },
        ),
    ]
