"""
Migration for Store model and domain changes.

Includes schema adjustments for multi-tenant architecture.
"""

# Generated by Django 5.2.2 on 2025-06-16 02:38

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for Store and domain changes."""

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[django_tenants.postgresql_backend.base._check_schema_name],
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Store name", max_length=100, verbose_name="Name"),
                ),
                (
                    "created_on",
                    models.DateField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary contact email",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=20,
                        null=True,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the store is active",
                        verbose_name="Active",
                    ),
                ),
                (
                    "on_trial",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the store is in trial period",
                        verbose_name="On trial",
                    ),
                ),
                (
                    "trial_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the trial period ends",
                        null=True,
                        verbose_name="Trial end date",
                    ),
                ),
                (
                    "paid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date until which the store has paid",
                        null=True,
                        verbose_name="Paid until",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store",
                "verbose_name_plural": "Stores",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="domain",
            options={
                "ordering": ["domain"],
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
            },
        ),
        migrations.AlterField(
            model_name="domain",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this is the primary domain for the store",
                verbose_name="Primary domain",
            ),
        ),
        migrations.AlterField(
            model_name="domain",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="tenants.store",
            ),
        ),
        migrations.DeleteModel(
            name="Tenant",
        ),
    ]
