"""Pydantic schemas package for TechStore SaaS."""

from .auth import LoginRequest, TokenResponse, UserCreate, UserResponse
from .base import (
    BaseSchema,
    ErrorResponse,
    PaginationParams,
    ResponseSchema,
    TimestampSchema,
)
from .cash_closing import (
    CashClosingCreate,
    CashClosingFinalize,
    CashClosingList,
    CashClosingResponse,
    CashClosingSummary,
    CashClosingUpdate,
    DailySummary,
)
from .product import (
    Category,
    CategoryCreate,
    CategoryUpdate,
    Product,
    ProductCreate,
    ProductImage,
    ProductImageCreate,
    ProductList,
    ProductSupplier,
    ProductSupplierCreate,
    ProductUpdate,
)
from .repair import (
    PhotoType,
    RepairComplete,
    RepairCreate,
    RepairDeliver,
    RepairDiagnosis,
    RepairInDB,
    RepairListResponse,
    RepairPartCreate,
    RepairPartResponse,
    RepairPhotoCreate,
    RepairPhotoResponse,
    RepairResponse,
    RepairSearchParams,
    RepairStatistics,
    RepairStatus,
    RepairStatusHistoryCreate,
    RepairStatusHistoryResponse,
    RepairStatusUpdate,
    RepairUpdate,
)
from .sale import (
    ProductSearchResult,
    ReceiptData,
    SaleCreate,
    SaleInDB,
    SaleItemCreate,
    SaleItemInDB,
    SaleItemResponse,
    SaleListResponse,
    SaleResponse,
    SaleSummary,
    SaleUpdate,
    VoidSaleRequest,
)
from .supplier import Supplier, SupplierCreate, SupplierList, SupplierUpdate
from .warranty import (
    CoverageType,
    WarrantyCheckRequest,
    WarrantyCheckResponse,
    WarrantyClaimCreate,
    WarrantyClaimResponse,
    WarrantyClaimUpdate,
    WarrantyCreate,
    WarrantyListResponse,
    WarrantyResponse,
    WarrantySearchParams,
    WarrantyStatistics,
    WarrantyStatus,
    WarrantyUpdate,
    WarrantyVoid,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "UserCreate",
    "UserResponse",
    # Base
    "BaseSchema",
    "TimestampSchema",
    "ResponseSchema",
    "ErrorResponse",
    "PaginationParams",
    # Cash Closing
    "CashClosingCreate",
    "CashClosingUpdate",
    "CashClosingResponse",
    "CashClosingSummary",
    "CashClosingFinalize",
    "CashClosingList",
    "DailySummary",
    # Product
    "Category",
    "CategoryCreate",
    "CategoryUpdate",
    "Product",
    "ProductCreate",
    "ProductUpdate",
    "ProductList",
    "ProductImage",
    "ProductImageCreate",
    "ProductSupplier",
    "ProductSupplierCreate",
    # Supplier
    "Supplier",
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierList",
    # Sale
    "SaleCreate",
    "SaleUpdate",
    "SaleInDB",
    "SaleResponse",
    "SaleListResponse",
    "SaleItemCreate",
    "SaleItemInDB",
    "SaleItemResponse",
    "ProductSearchResult",
    "VoidSaleRequest",
    "ReceiptData",
    "SaleSummary",
    # Repair
    "RepairStatus",
    "PhotoType",
    "RepairCreate",
    "RepairUpdate",
    "RepairDiagnosis",
    "RepairStatusUpdate",
    "RepairComplete",
    "RepairDeliver",
    "RepairInDB",
    "RepairResponse",
    "RepairListResponse",
    "RepairPartCreate",
    "RepairPartResponse",
    "RepairPhotoCreate",
    "RepairPhotoResponse",
    "RepairStatusHistoryCreate",
    "RepairStatusHistoryResponse",
    "RepairSearchParams",
    "RepairStatistics",
    # Warranty
    "WarrantyStatus",
    "CoverageType",
    "WarrantyCreate",
    "WarrantyUpdate",
    "WarrantyVoid",
    "WarrantyClaimCreate",
    "WarrantyClaimUpdate",
    "WarrantyResponse",
    "WarrantyClaimResponse",
    "WarrantyListResponse",
    "WarrantySearchParams",
    "WarrantyStatistics",
    "WarrantyCheckRequest",
    "WarrantyCheckResponse",
]
