repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
            ^.pre-commit/|
            ^.cursor/|
            ^scripts/version.sh$|
            ^docs/|
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^.pre-commit/|
            ^.cursor/|
            ^scripts/version.sh$|
            ^docs/|
          )
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=500]
        exclude: |
          (?x)(
            ^.pre-commit/|
            ^.cursor/|
            ^frontend/package-lock.json$|
            ^techstore/frontend/package-lock.json$
          )

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--max-line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]
        exclude: |
          (?x)(
            ^.pre-commit/|
            ^.cursor/
          )
