"""Add payment_type field to payments table

Revision ID: 08e1703b528d
Revises: c4a268f1dfc2
Create Date: 2025-08-12 23:24:12.867649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e1703b528d'
down_revision: Union[str, Sequence[str], None] = 'c4a268f1dfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type
    paymenttype_enum = sa.Enum('PAYMENT', 'ADVANCE_PAYMENT', 'REFUND', name='paymenttype')
    paymenttype_enum.create(op.get_bind())

    # Add column with default value
    op.add_column('payments', sa.Column('payment_type', paymenttype_enum, nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE payments SET payment_type = 'PAYMENT' WHERE payment_type IS NULL")

    # Make column not nullable
    op.alter_column('payments', 'payment_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_type')

    # Drop enum type
    paymenttype_enum = sa.Enum('PAYMENT', 'ADVANCE_PAYMENT', 'REFUND', name='paymenttype')
    paymenttype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
