"""Add change_amount column to sales table

Revision ID: 3fa1191cd4d7
Revises: eeaba3b9fb9f
Create Date: 2025-11-19 21:19:38.126124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa1191cd4d7'
down_revision: Union[str, Sequence[str], None] = 'eeaba3b9fb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value first, then make it non-nullable
    op.add_column('sales', sa.Column('change_amount', sa.DECIMAL(precision=10, scale=2),
                                      nullable=False, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'change_amount')
    # ### end Alembic commands ###
