"""add payment method breakdown and custom pricing

Revision ID: 40c93e1db298
Revises: db1b8739bca5
Create Date: 2025-08-30 06:47:01.145940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c93e1db298'
down_revision: Union[str, Sequence[str], None] = 'db1b8739bca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_closings', sa.Column('sales_cash', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Cash sales total'))
    op.add_column('cash_closings', sa.Column('sales_credit', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Credit sales total'))
    op.add_column('cash_closings', sa.Column('sales_transfer', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Transfer sales total'))
    op.add_column('cash_closings', sa.Column('sales_mixed', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Mixed payment sales total'))
    op.add_column('cash_closings', sa.Column('expenses_cash', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Cash expenses total'))
    op.add_column('cash_closings', sa.Column('expenses_transfer', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Transfer expenses total'))
    op.add_column('cash_closings', sa.Column('expenses_card', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Card expenses total'))
    op.add_column('sale_items', sa.Column('is_custom_price', sa.Boolean(), nullable=False, server_default='false', comment='Whether custom price was used'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_items', 'is_custom_price')
    op.drop_column('cash_closings', 'expenses_card')
    op.drop_column('cash_closings', 'expenses_transfer')
    op.drop_column('cash_closings', 'expenses_cash')
    op.drop_column('cash_closings', 'sales_mixed')
    op.drop_column('cash_closings', 'sales_transfer')
    op.drop_column('cash_closings', 'sales_credit')
    op.drop_column('cash_closings', 'sales_cash')
    # ### end Alembic commands ###
