"""enhance_categories_with_hierarchy

Revision ID: 537566f02176
Revises: 7d1c1d54160f
Create Date: 2025-07-30 21:33:07.843692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537566f02176'
down_revision: Union[str, Sequence[str], None] = '7d1c1d54160f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('categories', sa.Column('display_order', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('full_path', sa.String(length=500), nullable=True))
    op.add_column('categories', sa.Column('level', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_index(op.f('ix_categories_full_path'), 'categories', ['full_path'], unique=False)
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_unique_constraint('uq_category_name_parent', 'categories', ['name', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_name_parent', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_full_path'), table_name='categories')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'level')
    op.drop_column('categories', 'full_path')
    op.drop_column('categories', 'display_order')
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
