"""Add mixed payment portions to cash_closings

Revision ID: 739832c39d62
Revises: fix_enum_case_001
Create Date: 2025-12-29 19:41:54.352025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '739832c39d62'
down_revision: Union[str, Sequence[str], None] = 'fix_enum_case_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_closings', sa.Column('sales_mixed_cash', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Cash portion from mixed payment sales'))
    op.add_column('cash_closings', sa.Column('sales_mixed_transfer', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Transfer portion from mixed payment sales'))
    op.add_column('cash_closings', sa.Column('sales_mixed_card', sa.DECIMAL(precision=10, scale=2), nullable=False, server_default='0.00', comment='Card portion from mixed payment sales'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_closings', 'sales_mixed_card')
    op.drop_column('cash_closings', 'sales_mixed_transfer')
    op.drop_column('cash_closings', 'sales_mixed_cash')
    # ### end Alembic commands ###
