"""Add cash opening fields to cash_closing table

Revision ID: 80d29f127897
Revises: ccc3657c6dfc
Create Date: 2025-08-02 04:00:37.197178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d29f127897'
down_revision: Union[str, Sequence[str], None] = 'ccc3657c6dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_closings', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True, comment='When cash register was opened'))
    op.add_column('cash_closings', sa.Column('opened_by', sa.Integer(), nullable=True, comment='User who opened'))
    op.create_foreign_key(None, 'cash_closings', 'users', ['opened_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cash_closings', type_='foreignkey')
    op.drop_column('cash_closings', 'opened_by')
    op.drop_column('cash_closings', 'opened_at')
    # ### end Alembic commands ###
