"""Add is_service field to products for repair integration

Revision ID: ab0541798b68
Revises: 94cd63111bbe
Create Date: 2025-09-28 20:12:54.340362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0541798b68'
down_revision: Union[str, Sequence[str], None] = '94cd63111bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_service', sa.Boolean(), nullable=True, server_default='false'))
    op.execute('UPDATE products SET is_service = false WHERE is_service IS NULL')
    op.alter_column('products', 'is_service', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_service')
    # ### end Alembic commands ###
