"""Change default tax_rate to 0.00 for all products

Revision ID: c4a268f1dfc2
Revises: a0259d3d35a6
Create Date: 2025-08-12 23:08:28.926928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4a268f1dfc2'
down_revision: Union[str, Sequence[str], None] = 'a0259d3d35a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Update all existing products to have 0% tax rate
    op.execute("UPDATE products SET tax_rate = 0.00")

    # Change the default value for the tax_rate column
    op.alter_column('products', 'tax_rate',
                    server_default='0.00',
                    existing_type=sa.DECIMAL(precision=5, scale=2),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the default value for the tax_rate column
    op.alter_column('products', 'tax_rate',
                    server_default='16.00',
                    existing_type=sa.DECIMAL(precision=5, scale=2),
                    existing_nullable=False)

    # Optionally update products back to 16% (commented out to avoid data loss)
    # op.execute("UPDATE products SET tax_rate = 16.00")
    # ### end Alembic commands ###
