"""Add mixed payment component fields to Sale model

Revision ID: e190c34b6a04
Revises: 40c93e1db298
Create Date: 2025-09-06 22:39:18.641156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e190c34b6a04'
down_revision: Union[str, Sequence[str], None] = '40c93e1db298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('cash_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('transfer_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('card_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('sales', sa.Column('credit_amount', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'credit_amount')
    op.drop_column('sales', 'card_amount')
    op.drop_column('sales', 'transfer_amount')
    op.drop_column('sales', 'cash_amount')
    # ### end Alembic commands ###
