version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspace
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/techstore_db
      - GIT_AUTHOR_NAME=lucast086
      - GIT_AUTHOR_EMAIL=turlettilucasdev@gmail.com
      - GIT_COMMITTER_NAME=lucast086
      - GIT_COMMITTER_EMAIL=turlettilucasdev@gmail.com
    depends_on:
      - db
    networks:
      - techstore_network

  # PostgreSQL para FastAPI
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techstore_db
    ports:
      - "5433:5432"
    networks:
      - techstore_network

volumes:
  postgres-data:

networks:
  techstore_network:
    driver: bridge
