"""
Migration to add phone field to User and create UserAuditLog model.

This migration updates the User model and adds audit logging support.
"""

# Generated by Django 5.2.2 on 2025-06-16 02:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add phone field and UserAuditLog model."""

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="phone number"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.CreateModel(
            name="UserAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Type of action performed",
                        max_length=50,
                        verbose_name="action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the action was performed",
                        verbose_name="timestamp",
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Additional details about the action",
                        verbose_name="details",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address from which the action was performed",
                        null=True,
                        verbose_name="IP address",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/client information",
                        verbose_name="user agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user audit log",
                "verbose_name_plural": "user audit logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["user", "action"], name="users_usera_user_id_6525b9_idx"),
                    models.Index(fields=["timestamp"], name="users_usera_timesta_2ee886_idx"),
                ],
            },
        ),
    ]
