[tool.poetry]
name = "techstore"
version = "0.1.0"
description = "Sistema SaaS para gestión de comercios técnicos"
authors = ["lucast086 <turlettilucasdev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
